### ISSUE TITLE
焦点通知开发者文档

### ISSUE THREAD

**Issue by 1084233320** [wuyou-123/FocusNotifLyric#1]
抱歉以这种方式联系您
我是一名客户端开发，我也想要适配澎湃os的焦点通知，可是并没有找到官方的开发者文档。请问您是如何开发的呢？

**Comment by wuyou-123** [comment]
我也没有文档,我是通过反编译查看其他支持焦点通知的应用拿到的发送焦点通知的代码
并且这个焦点通知是有白名单的,其他客户端应用是不允许发送焦点通知的

**Comment by 1084233320** [comment]
> 我也没有文档,我是通过反编译查看其他支持焦点通知的应用拿到的发送焦点通知的代码 并且这个焦点通知是有白名单的,其他客户端应用是不允许发送焦点通知的

非常感谢您的回复
那如果有“白名单”的概念的话，您的焦点通知是如何实现的？开root无视限制？or 你通过申请，应用在白名单内了嘛？

**Comment by wuyou-123** [comment]
这个项目是个Xposed框架,通过Hook的方式修改了白名单的判断条件

**Comment by 1084233320** [comment]
> Xposed

理解了，非常感谢您的帮助
